# Generated by Django 4.0.3 on 2022-03-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='timezone',
            field=models.CharField(default='UTC', max_length=6),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
